# Generated by Django 5.2.4 on 2025-07-04 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g. GET question1.views.ProjectViewSet.list', max_length=180)),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=8)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='question2_a_timesta_84c1b8_idx'), models.Index(fields=['user', 'timestamp'], name='question2_a_user_id_e571f1_idx')],
            },
        ),
    ]
